<?php

/*
 * @file
 * Contains sf_drupal.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * {@inheritdoc}
 */
function sf_drupal_entity_presave(Drupal\Core\Entity\EntityInterface $entity)
{
    switch ($entity->bundle()) {
        // Here we push data only for our content type
        case 'lead_detail':
            $data_push_service = \Drupal::service('sf_drupal.data_push');
            $data_push_service->sendDataToSalesForce($entity->get('title')->value, $entity->get('body')->value);
        break;
    }
}

/**
 * Implements hook_help().
 */
function sf_drupal_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    case 'help.page.sf_drupal':

        $url = Url::fromUri('https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_defining_remote_access_applications.htm');
        $sales_force_help_page_link = \Drupal::l(t('Sales Force API Help Page'), $url);

        $output = '';
        $output .= '<h3>'.t('About').'</h3>';
        $output .= '<p>'.t('The Salesforce Drupal module Push Lead data to Salesforce Account Object').'</p>';
        $output .= '<h3>'.t('Uses').'</h3>';
        $output .= '<ul><li>'.t('You would need Salesforce API Login URL. Usually it is "https://login.salesforce.com/services/oauth2/token"').'</li>';
        $output .= '<li>'.t('You would need Salesforce API Consumer Key and Secrete key.');
        $output .= '<p>'.t('Use the following steps to create a new connected app.').'</p>';
        $output .= '<ol><li>'.t('Use Salesforce to create a new connected app.').'</p>';
        $output .= '<ul><li>'.t('In Lightning Experience, use the App Manager to create connected apps. From Setup, enter App in the Quick Find box, then select ');
        $output .= '<strong>'.t('App Manager.').'</strong>';
        $output .= t('Click ');
        $output .= '<strong>'.t('New Connected App').'</strong>.</li>';
        $output .= '<li>'.t('In Salesforce Classic, from Setup, enter Apps in the Quick Find box, then select ').'<strong>'.t('Apps').'</strong>'.t(' (under ').'<strong>'.t('Build').'</strong> | <strong>'.t('Create').'</strong>). '.t('Under Connected Apps, click ').'<strong>'.t('New').'</strong>.</li>';
        $output .= '</ul></li>';
        $output .= '<li>'.t('Enter the name of your application.').'</li>';
        $output .= '<li>'.t('Enter the contact email information, as well as any other information appropriate for your application.').'</li>';
        $output .= '<li>'.t('Select <strong>Enable OAuth Settings</strong>.').'</li>';
        $output .= '<li>'.t('Enter a Callback URL. Depending on which OAuth flow you use, this is typically the URL that a user’s browser is redirected to after successful authentication. As this URL is used for some OAuth flows to pass an access token, the URL must use secure HTTP (HTTPS) or a custom URI scheme. Separate multiple callback URLs with line breaks.').'</li>';
        $output .= '<li>'.t('Add all supported OAuth scopes to <strong>Selected OAuth Scopes</strong>. These scopes refer to permissions given by the user running the connected app.').'</li>';
        $output .= '<li>'.t('Enter a URL for Info URL. This is where the user can go for more information about your application.').'</li>';
        $output .= '<li>'.t('Click ').'<strong>'.t('Save').'</strong>. '.t('The Consumer Key is created and displayed, and the Consumer Secret is created (click the link to reveal it).').'</li>';
        $output .= '</ol></li><p>'.t('For Other Details Please check: ').$sales_force_help_page_link;
        $output .= '<li>'.t('Use your App login Username.').'</li>';
        $output .= '<li>'.t('Use your App login password appended with App Security Token.');
        $output .= '<p>'.t('Use the following steps to create a new Security Token.').'</p>';
        $output .= '<ul><li>'.t('Login to your orgnistaion and Navigate to At the top navigation bar go to <your name > My Settings > Personal  >  Reset My Security Token.').'</li>';
        $output .= '<li>'.t('And click on "Reset Security Token". Clicking the button invalidates your existing token. After resetting your token, It will be mail to the user mai ID').'</li>';
        $output .= '</ul></li>';
        $output .= '</ul>';

      return $output;
  }
}
